Improve CS.
Use "ubuntu:latest" insteadof "ubuntu:16.04".

Use "timonier/version-lister".

diff --git a/bin/installer b/bin/installer
--- a/bin/installer
+++ b/bin/installer
@@ -1,53 +1,66 @@
 #!/bin/sh
-set -x
+set -eux
+
+# Check environment
 
 fail() {
-    echo $1 1>&2
-    echo "Usage: $0 [install|uninstall]" 1>&2
+    echo "$1" 1>&2
+    echo "Usage: $(basename "$0") [install|uninstall] (apm|atom)*" 1>&2
     exit 1
 }
 
-install() {
-    docker run \
-        -v /:/host \
-        --entrypoint sh \
-        --rm \
-        ${IMAGE:-timonier/atom}:${TAG:-1.7.4} -c "cp $1 /host/$1"
-}
-
-if [ $# -lt 1 ] ; then
+if [ "$#" -lt 1 ] ; then
     fail "Invalid number of arguments."
 fi
 
-if [ $(id -u) -ne 0 ] ; then
+if [ "$(id --user)" -ne 0 ] ; then
     fail "Impossible to prepare the system without root privileges."
 fi
 
-if [ $(uname) != "Linux" ] ; then
+if [ "$(uname)" != "Linux" ] ; then
     fail "Impossible to prepare another operating system than Linux."
 fi
 
+# Run installer
+
+install() {
+    docker run \
+        --entrypoint sh \
+        --rm \
+        --volume /:/host \
+        "${IMAGE:-timonier/atom}:${TAG:-latest}" -c "cp '$1' '/host/$1'"
+}
+
 case $1 in
     install )
-        curl -sLo /usr/local/bin/apm "https://github.com/timonier/atom/raw/master/bin/apm"
-        chmod +x /usr/local/bin/apm
+        if [ "$#" -eq 1 ] || echo "$*" | grep --quiet apm ; then
+            curl --location --output /usr/local/bin/apm "https://github.com/timonier/atom/raw/master/bin/apm"
+            chmod +x /usr/local/bin/apm
+        fi
 
-        curl -sLo /usr/local/bin/atom "https://github.com/timonier/atom/raw/master/bin/atom"
-        chmod +x /usr/local/bin/atom
+        if [ "$#" -eq 1 ] || echo "$*" | grep --quiet atom ; then
+            curl --location --output /usr/local/bin/atom "https://github.com/timonier/atom/raw/master/bin/atom"
+            chmod +x /usr/local/bin/atom
 
-        install /usr/share/applications/atom.desktop
-        sed -i 's@/usr/share/atom/@@g' /usr/share/applications/atom.desktop
+            install /usr/share/applications/atom.desktop
+            sed -i "s@/usr/share/atom/@@g" /usr/share/applications/atom.desktop
 
-        install /usr/share/pixmaps/atom.png
+            install /usr/share/pixmaps/atom.png
+        fi
     ;;
 
     uninstall )
-        rm -f /usr/local/bin/apm
-        rm -f /usr/local/bin/atom
-        rm -f /usr/share/applications/atom.desktop
-        rm -f /usr/share/pixmaps/atom.png
+        if [ "$#" -eq 1 ] || echo "$*" | grep --quiet apm ; then
+            rm --force /usr/local/bin/apm
+        fi
+
+        if [ "$#" -eq 1 ] || echo "$*" | grep --quiet atom ; then
+            rm --force /usr/local/bin/atom
+            rm --force /usr/share/applications/atom.desktop
+            rm --force /usr/share/pixmaps/atom.png
+        fi
     ;;
 
     * )
-        fail "Argument $1 is invalid."
+        fail "Argument \"$1\" is invalid."
 esac
